version: 0.0
os: linux

files:
  - source: /
    destination: /home/elijah/server

permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root

hooks:
  BeforeInstall:
    - location: server_clear
      timeout: 300
      runas: root

  AfterInstall:
    - location: fix_privileges
      timeout: 300


  ApplicationStart:
    - location: server_start
      timeout: 21


  ApplicationStop:
    - location: server_stop
      timeout: 20
      runas: root
