version: 0.0
os: linux

files:
  - source: /
    destination: /home/elijah/server

hooks:
  BeforeInstall:
    - location: server_clear.sh
      timeout: 300

  AfterInstall:
    - location: fix_privileges.sh
      timeout: 300

  ApplicationStart:
    - location: server_start.sh
      timeout: 21


  ApplicationStop:
    - location: server_stop.sh
      timeout: 20

