version: 0.0
os: linux

files:
  - source: /
    destination: /home/elijah/server

permissions:
  - object: /
    pattern: "**"
    owner: elijah
    group: elijah

hooks:
  BeforeInstall:
    - location: scripts/server_clear.sh
      timeout: 300
      runas: elijah
  AfterInstall:
    - location: scripts/fix_privileges.sh
      timeout: 300
      runas: elijah
  ApplicationStart:
    - location: scripts/server_start.sh
      timeout: 20
      runas: elijah
  ApplicationStop:
    - location: scripts/server_stop.sh
      timeout: 20
      runas: elijah