version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk-21
  build:
    commands:
      - echo Building the application...
      - ./mvnw clean package
artifacts:
  files:
    - target/my-app.jar

