version: 0.2
phases:
  install:
    commands:
      - apt-get update; apt-get install -y java-17-amazon-corretto-jdk
      - update-alternatives --auto javac
      - update-alternatives --auto java
  build:
    commands:
      - echo Building the application...
      - chmod +x mvnw
      - ./mvnw clean package
artifacts:
  files:
    - target/my-app.jar
    - scripts/*
    - appspec.yml
  discard-paths: yes

